### ISSUE TITLE
JWP Draft Publish TODO list

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#53]
This is tracking items to be done on the main JWP draft before being published as an IETF ID

- [x] Decide on example (BBS vs. SU)
- [x] Update SU-JWS alg naming (s/SU/JWS/)
- [x] Finish MAC alg #48 
- [x] Add language for #27 
- [x] Formalize language
- [x] Verify/add all references
- [ ] Decide on #50 
- [x] Introduce JPA/JPT #20 
- [x] #19 
- [ ] #7 
- [x] #8 
- [x] #11

**Comment by dwaite** [comment]
aged pre-publication list. Closing in lieu of milestones
